#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     drivemotorR,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     drivemotorL,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     conveyormotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     liftmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     pullupmotorR,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     pullupmotorL,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// main() - the main task for the robot. this is an infinite loop - it will run until halted.
task main() {
	while(true) { // infinite loop
		// test code for controller 1
		motor[motorD] = 30;
		motor[motorE] = 30;
	}
}
